import { linkMelonlyMemberAction, saveDiscordTeamRoleMappingAction, saveMelonlyRoleAction, syncMelonlyAction } from "@/app/actions/melonly";
import { PortalShell } from "@/components/portal-shell";
import { ReliableActionForm } from "@/components/reliable-action-form";
import { SubmitButton } from "@/components/submit-button";
import { requirePermission } from "@/lib/authz";
import { melonlyConfigured } from "@/lib/melonly";
import { prisma } from "@/lib/prisma";
import { formatDateTime } from "@/lib/site";

export const dynamic = "force-dynamic";

const mappingLabels: Record<string, string> = { STRIKE_1: "1. Strike", STRIKE_2: "2. Strike", STRIKE_3: "3. Strike / Entfernung", UPRANK_BLOCK: "Up-Rank-Sperre" };

export default async function MelonlyAdminPage() {
  const { authorization } = await requirePermission("melonly.manage");
  const [roles, mappings, discordRoles, members, users, lastMember, jobCounts] = await Promise.all([
    prisma.melonlyRole.findMany({ orderBy: [{ position: "desc" }, { name: "asc" }] }),
    prisma.discordTeamRoleMapping.findMany({ include: { discordRole: true }, orderBy: { key: "asc" } }),
    prisma.discordRole.findMany({ orderBy: [{ position: "desc" }, { name: "asc" }] }),
    prisma.melonlyMember.findMany({ where: { active: true }, include: { user: true, role: true }, orderBy: { displayName: "asc" }, take: 500 }),
    prisma.user.findMany({ where: { OR: [{ discordId: { not: null } }, { robloxUserId: { not: null } }] }, orderBy: { name: "asc" }, take: 1000 }),
    prisma.melonlyMember.findFirst({ orderBy: { lastSyncedAt: "desc" }, select: { lastSyncedAt: true } }),
    prisma.discordRoleJob.groupBy({ by: ["status"], _count: true }),
  ]);
  return <PortalShell authorization={authorization} title="Melonly & Team" description="Wochenzeiten, Rangfolge und Discord-Rollen für Strikes und Up-Rank-Sperren verwalten." section="admin">
    <section className="mb-6 grid gap-4 md:grid-cols-3"><div className="surface p-5"><p className="text-xs uppercase tracking-[0.12em] text-[#777d81]">API</p><p className="mt-2 text-lg font-semibold">{melonlyConfigured() ? "Konfiguriert" : "Token fehlt"}</p></div><div className="surface p-5"><p className="text-xs uppercase tracking-[0.12em] text-[#777d81]">Aktive Mitglieder</p><p className="mt-2 text-2xl font-semibold">{members.length}</p></div><div className="surface p-5"><p className="text-xs uppercase tracking-[0.12em] text-[#777d81]">Letzter Abgleich</p><p className="mt-2 text-sm font-semibold">{lastMember ? formatDateTime(lastMember.lastSyncedAt) : "Noch nie"}</p></div></section>
    <ReliableActionForm action={syncMelonlyAction} className="surface mb-6 p-5"><p className="mb-4 text-sm leading-6 text-[#91979b]">Liest Mitglieder, Rollen, Schichten und LoAs serverseitig aus der Melonly-API. Der API-Token wird nie angezeigt.</p><SubmitButton pendingText="Melonly wird synchronisiert …">Jetzt synchronisieren</SubmitButton></ReliableActionForm>
    <section className="surface mb-6 p-6"><h2 className="text-xl font-semibold">Wochenzeiten & Rangfolge</h2><p className="mt-2 text-sm text-[#858b90]">Zeitangaben werden in Minuten gespeichert. Für jede Rolle kann die nächste Up-Rank-Stufe hinterlegt werden.</p><div className="mt-5 grid gap-3">{roles.length ? roles.map((role) => <ReliableActionForm key={role.id} action={saveMelonlyRoleAction} className="grid gap-3 rounded-xl border border-white/[0.07] p-4 lg:grid-cols-[1fr_180px_1fr_auto] lg:items-end"><input type="hidden" name="id" value={role.id} /><div><span className="text-xs text-[#777d81]">Melonly-Rolle</span><p className="mt-1 font-semibold">{role.name}</p></div><label className="field-label">Sollzeit/Woche (Min.)<input className="field" type="number" min="0" max="10080" name="weeklyTargetMinutes" defaultValue={role.weeklyTargetMinutes} /></label><label className="field-label">Nächste Rolle<select className="field" name="nextRoleId" defaultValue={role.nextRoleId || ""}><option value="">Keine</option>{roles.filter((candidate) => candidate.id !== role.id).map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</select></label><SubmitButton variant="secondary">Speichern</SubmitButton></ReliableActionForm>) : <p className="text-sm text-[#858b90]">Nach der ersten Synchronisierung erscheinen hier die Melonly-Rollen.</p>}</div></section>
    <details className="surface mb-6 p-6"><summary className="cursor-pointer text-xl font-semibold">Melonly-Mitglieder zuordnen</summary><p className="mt-3 text-sm leading-6 text-[#858b90]">Falls Melonly nur eine interne Mitglieds-ID liefert, ordne das Mitglied einmalig einem Website-Nutzer zu. Discord- und Roblox-Daten werden danach aus dessen authentifiziertem Profil übernommen.</p><div className="mt-5 grid gap-3">{members.map((member) => <ReliableActionForm key={member.id} action={linkMelonlyMemberAction} className="grid gap-3 rounded-xl border border-white/[0.07] p-4 lg:grid-cols-[1fr_1.5fr_auto] lg:items-center"><input type="hidden" name="memberId" value={member.id} /><div><p className="font-semibold">{member.displayName}</p><p className="mt-1 text-xs text-[#777d81]">{member.role?.name || "Keine Melonly-Rolle"} · {member.externalId}</p></div><select className="field" name="userId" defaultValue={member.userId || ""}><option value="">Nicht zugeordnet</option>{users.map((user) => <option key={user.id} value={user.id}>{user.discordDisplayName || user.discordUsername || user.robloxDisplayName || user.robloxName || user.name}</option>)}</select><SubmitButton variant="secondary">Zuordnung speichern</SubmitButton></ReliableActionForm>)}</div></details>
    <section className="surface mb-6 p-6"><h2 className="text-xl font-semibold">Discord-Rollenautomatik</h2><p className="mt-2 text-sm leading-6 text-[#858b90]">Die Website legt Aufträge an. Dein Bot ruft <code>/api/bot/discord/role-jobs</code> mit dem bekannten Bearer-Token ab und bestätigt sie anschließend. Up-Ranks und Teamentfernungen bleiben bewusste Staff-Entscheidungen.</p><div className="mt-5 grid gap-3">{mappings.map((mapping) => <ReliableActionForm key={mapping.key} action={saveDiscordTeamRoleMappingAction} className="grid gap-3 rounded-xl border border-white/[0.07] p-4 lg:grid-cols-[200px_1fr_auto_auto] lg:items-center"><input type="hidden" name="key" value={mapping.key} /><strong className="text-sm">{mappingLabels[mapping.key] || mapping.key}</strong><select className="field" name="discordRoleId" defaultValue={mapping.discordRoleId || ""}><option value="">Nicht verknüpft</option>{discordRoles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select><label className="flex items-center gap-2 text-xs"><input type="checkbox" name="enabled" defaultChecked={mapping.enabled} /> Aktiv</label><SubmitButton variant="secondary">Verknüpfen</SubmitButton></ReliableActionForm>)}</div></section>
    <section className="surface p-6"><h2 className="text-xl font-semibold">Rollenaufträge</h2><div className="mt-4 flex flex-wrap gap-2">{jobCounts.map((group) => <span key={group.status} className="badge">{group.status}: {group._count}</span>)}</div></section>
  </PortalShell>;
}
